version: "3.8"

services:
  e-commerce-core:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - APP_NAME=e-commerce-core
    environment:
      - NODE_ENV=production
      - APP_NAME=e-commerce-core
    # command: npm run start:prod:core
    ports:
      - 3000:3000 # This instructs Docker Compose to map port 3000 on the host to port 3000 on the container
    volumes:        
      - ./libs:/usr/src/app/libs
      - ./package.json:/usr/src/app/package.json    
      - ./tsconfig.json:/usr/src/app/tsconfig.json   
      - ./apps/e-commerce-core:/usr/src/app/apps/e-commerce-core
      - ./apps/users:/usr/src/app/apps/users
    depends_on:
      - users
    env_file: # .env file that sits beside this file
      - .env
    networks:
     - my-network
  users:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - APP_NAME=users
    environment:
      - NODE_ENV=production
      - APP_NAME=users
    # command: npm run start:prod:users
    ports:
      - 3001:3001/tcp # This instructs Docker Compose to map port 3000 on the host to port 3000 on the container
    volumes:        
      - ./libs:/usr/src/app/libs
      - ./package.json:/usr/src/app/package.json    
      - ./tsconfig.json:/usr/src/app/tsconfig.json   
      - ./apps/users:/usr/src/app/apps/users
    env_file: # .env file that sits beside this file
      - .env
    networks:
     - my-network
networks:
  my-network:
    driver: bridge