export enum Permissions {
  VIEW_USERS = 'VIEW_USERS',
  CREATE_PRODUCT = 'CREATE_PRODUCT',
  UPDATE_PRODUCT = 'UPDATE_PRODUCT',
  DELETE_PRODUCT = 'DELETE_PRODUCT',
  ACTIVATE_PRODUCT = 'ACTIVATE_PRODUCT',
  VIEW_ORDERS = 'VIEW_ORDERS',
}
